version: '3'
services:
  web:
    build: .
    container_name: notetaking_app
    ports:
      - 3000:3000
    volumes:
      - $PWD:/usr/src/app
    command: npm run dev:start
    working_dir: /usr/src/app
    environment:
      - DATABASE_URL=mongodb://database:27017
    depends_on:
      - database
  database:
    image: mongo:3.6.3
    container_name: notetaking_app_database
  npm_install:
    image: node:8-alpine
    command: npm install
    working_dir: /usr/src/app
    volumes:
      - $PWD:/usr/src/app
